name: Testing Workflow Variables
on: 
  workflow_dispatch

env:
 cloud: google-cloud
jobs:
   test_context_variables:
    runs-on: ubuntu-latest
    steps:
     - name: "Checking Context Variables"
       run: |
         echo "Repository Name : ${{github.repository}}"
         echo "Workflow Name: ${{github.workflow}}"
         echo "Triggered By: ${{github.triggering_actor}}"
      
