name: 'Terraform'

on:
  push:
     branches: ["main"]
  pull_request:

permissions: 
    contents: read

jobs:

  terraform:
     name: 'Terraform'
     runs-on: self-hosted

     defaults:
      run:
        shell: bash
     steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{secrets.GITHUB_TOKEN}}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        



        
