name: 'Terraform'

on:
  push:
     branches: [ "main" ]
  pull_request:

permissions: 
    contents: read

jobs:

  terraform:
     name: 'Terraform'
     runs-on: self-hosted

     defaults:
      run:
        shell: bash
     steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 'Authenticate to GCP'
         uses: 'google-github-actions/auth@v2'
         with:
           credentials_json: ${{ secrets.GCP_SA_KEY }} # or workload identity config
           scopes: 'https://googleapis.com'
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        



        
